name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '17'
      - run: ./gradlew apiCheck build
      - uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: './tila-core/build/test-results/testDebugUnitTest/TEST*.xml'
